config/routes.rb
Stan::Application.routes.draw do
  resources :trips

  match 'rss' => 'trips#feed', :as => 'rss'
  match 'favorites' => 'trips#favorites', :as => 'favorites'
  match 'movie' => 'trips#movie', :as => 'movie'
  
  root :to => "trips#index"  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_attached_file :photo, 
                    :styles => { :medium => "400x400>", :thumb => "200x200>" },
                    :storage => :s3,
                    :bucket => 'stanbotz',
                    :s3_credentials => {
                      :access_key_id => ENV['S3_KEY'] || S3_KEY,
                      :secret_access_key => ENV['S3_SECRET'] || S3_SECRET
                    }
                    
  validates_presence_of :location
  validates_presence_of :description
  validates_presence_of :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  
  def authenticate
    uid = ENV['USER_ID'] || USER_ID
    pwd = ENV['PASSWORD'] || PASSWORD

    authenticate_or_request_with_http_basic do |username, password|
      username == uid && password == pwd
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :feed, :favorites, :movie]

  def feed
    @trips = Trip.all( :order => "id DESC", :limit => 20)
    respond_to do |format|
      format.xml
    end 
  end

  # GET /favorites
  # GET /favorites.xml
  def favorites
    @trips = Trip.where( :favorite => true ).order( :created_at )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trips }
    end
  end
  
  # GET /trips
  # GET /trips.xml
  def index
    @trips = Trip.order( 'created_at DESC' )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.xml
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.xml
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.xml
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to(@trip, :notice => 'Trip was successfully created.') }
        format.xml  { render :xml => @trip, :status => :created, :location => @trip }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.xml
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to(@trip, :notice => 'Trip was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.xml
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to(trips_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    not request.authorization.nil?
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stanley's Summer Trips
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = auto_discovery_link_tag :rss, "#{rss_path}.xml"
    = csrf_meta_tag
  %body
    #page_top &nbsp;
    #container
      #header
        #speach_bubble
          %div{ :class => 'triangle-border right' }
            Be sure to check out my 
            =link_to 'favorite pictures', favorites_path
            &nbsp;and 
            =link_to 'movie', movie_path
        %a{ :href => trips_path }
          =image_tag 'stan_medium.png'
          =image_tag 'title.png'
        .clear
      #content
        = yield
    #footer 
      An 
      =link_to 'edbotz', 'http://edbotz.us'
      creation ~ Source code on 
      =link_to 'github', 'https://github.com/ebot/stanley'

app/views/trips/_form.html.haml
= form_for( @trip, :html => { :multipart => true } ) do |f|
  - if @trip.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@trip.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @trip.errors.full_messages.each do |msg|
        %li= msg
  %table
    %tr
      %th= f.label :location
      %td= f.text_field :location
    %tr
      %th= f.label :favorite
      %td= f.radio_button :favorite, true
    %tr
      %th= f.label :photo
      %td=f.file_field :photo
    %tr
      %th= f.label :description
      %td= f.text_area :description

  .actions
    = f.submit
    = submit_tag "Cancel", :onClick => "history.back();return false;"

app/views/trips/edit.html.haml
= render 'form'

app/views/trips/favorites.html.haml
#about
  My name is Stan, and I had a blast traveling around the Philadelphia 
  area with Kayla and Lindsey.  I am very glad that Ansley decided to 
  send me to their house.  We got to go to lots of cool places this summer!  
  These are a few of my favorite photos from our adventures.  You can see 
  all of our adventures at 
  %a{ :href => root_path } http://stan.edbotz.us
  or watch our home movie at 
  %a{ :href => movie_path } http://stan.edbotz.us/movie
%ul.favorites
  - for trip in @trips
    %li
      .polaroid
        %a{ :href => trip_path( trip ), :title => trip.location }
          = image_tag trip.photo.url( :thumb )
      .description= trip.description
      .clear

app/views/trips/index.html.haml
%ul.polaroids
  - for trip in @trips
    %li
      %a{ :href => trip_path( trip ), :title => trip.location }
        = image_tag trip.photo.url( :thumb )
.clear

app/views/trips/movie.html.haml
#movie
  %iframe{ :width => '416', :height => '260', 
           :src => 'http://www.youtube.com/embed/wO4-MjvU-10',
           :frameborder => '0', :allowfullscreen => 'true' }

app/views/trips/new.html.haml
= render 'form'

app/views/trips/show.html.haml
.polaroid
  = image_tag @trip.photo.url(:medium)
  %br
  = @trip.location
#description
  - if logged_in?
    .toolbar  
      = link_to( t('Edit This Picture'), edit_trip_path(@trip) )
      = ' | '
      = link_to( t('Delete This Picture'), trip_path(@trip), :method => :delete, :confirm => "Are you sure?" )  
  %p= @trip.description
.clear